variables:
  S3_BUCKET_NAME: "imgor-v3.atlasnetworks.com"
  S3_BUCKET_STAGE_NAME: ""

stages:
  - build
  - deploy

# grunt_build_stage:
#   tags: 
#    - shell_runner
#   stage: build
#   script:
#     - npm install
#     - grunt dist --force
#   only:
#     - stage
#   artifacts:
#     paths:
#     - site/

build_prod:
  tags: 
   - shell_runner
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - master
  artifacts:
    paths:
    - build/


# deploy to stage:
#   tags: 
#     - docker_runner
#   stage: deploy
#   environment: stage
#   image: python:latest
#   script:
#     - pip install awscli
#     - aws s3 sync ./site/ s3://$S3_BUCKET_STAGE_NAME/ --exclude *.js --exclude assets/bower_*/* --exclude assets/lib/* --exclude assets/sass/* --include app.js
#     - aws configure set preview.cloudfront true
#     - aws cloudfront create-invalidation --distribution-id EJMHNWNMG1BKB --paths '/*'
#   only:
#     - stage


deploy to production:
  tags: 
    - docker_runner
  stage: deploy
  environment: production
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync ./build/ s3://$S3_BUCKET_NAME/ 
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id E308LQ9YPQS0BD --paths '/*'
  only:
    - master
