export const FINAL_STEP_GET_CATALOG_POSITIONS = 'FINAL_STEP_GET_CATALOG_POSITIONS';
export const FINAL_STEP_SET_DEFAULT_STATE = 'FINAL_STEP_SET_DEFAULT_STATE';

export const FINAL_STEP_REFUNDABLE_LOADING_TRUE = 'FINAL_STEP_REFUNDABLE_LOADING_TRUE';
export const FINAL_STEP_REFUNDABLE_LOADING_FALSE = 'FINAL_STEP_REFUNDABLE_LOADING_FALSE';

export const FINAL_STEP_REFUNDABLE_UPDATE = 'FINAL_STEP_REFUNDABLE_UPDATE';
export const FINAL_STEP_INSURANCE_PRICE_UPDATE = 'FINAL_STEP_INSURANCE_PRICE_UPDATE';
