export const INCREMENT_CURRENT_STEP = 'INCREMENT_CURRENT_STEP';
export const SET_MAX_STEP_VALUE = 'SET_MAX_STEP_VALUE';
export const CLOSE_EMAIL_MODAL = 'CLOSE_EMAIL_MODAL';
export const SET_STEPS_COUNTER = 'SET_STEPS_COUNTER';
