export const STEP_ONE_GET_CATALOG_GROUP = 'STEP_ONE_GET_CATALOG_GROUP';
export const STEP_ONE_SELECT_GROUP = 'STEP_ONE_SELECT_GROUP';
export const STEP_ONE_SET_TAB_INDEX = 'STEP_ONE_SET_TAB_INDEX';
export const STEP_ONE_SET_PRICE = 'STEP_ONE_SET_PRICE';
export const STEP_ONE_SET_CAMP_LENGTH = 'STEP_ONE_SET_CAMP_LENGTH';
