export const STEP_SIX_GET_CATALOG_AIRLINES = 'STEP_SIX_GET_CATALOG_AIRLINES';
export const STEP_SIX_GET_CATALOG_TRANSPORT = 'STEP_SIX_GET_CATALOG_TRANSPORT';
export const STEP_SIX_SET_DEFAULT_STATE = 'STEP_SIX_SET_DEFAULT_STATE';
export const STEP_SIX_SET_ARRIVAL_AIRLINES = 'STEP_SIX_SET_ARRIVAL_AIRLINES';
export const STEP_SIX_SET_DEPARTING_AIRLINES = 'STEP_SIX_SET_DEPARTING_AIRLINES';
