export const GET_CATALOG_GEAR = 'GET_CATALOG_GEAR';
export const STEP_FIVE_SET_GEAR = 'STEP_FIVE_SET_GEAR';
export const STEP_FIVE_INCREMENT_SELECTED_GEAR_QUANTITY = 'STEP_FIVE_INCREMENT_SELECTED_GEAR_QUANTITY';
export const STEP_FIVE_DECREMENT_SELECTED_GEAR_QUANTITY = 'STEP_FIVE_DECREMENT_SELECTED_GEAR_QUANTITY';
export const STEP_FIVE_SET_DEFAULT_STATE = 'STEP_FIVE_SET_DEFAULT_STATE';
export const STEP_FIVE_SELECT_DROPDOWN_OPTION = 'STEP_FIVE_SELECT_DROPDOWN_OPTION';
export const STEP_SIX_GET_CATALOG_GEAR_UPSELL_NEW = 'STEP_SIX_GET_CATALOG_GEAR_UPSELL_NEW';
