export const GET_CATALOG_CAMPS_CALENDAR = 'GET_CATALOG_CAMPS_CALENDAR';
export const STEP_TWO_SELECT_DATE = 'STEP_TWO_SELECT_DATE';
export const STEP_TWO_GET_CATALOG_CAMPS_HISTOGRAM = 'STEP_TWO_GET_CATALOG_CAMPS_HISTOGRAM';
export const STEP_TWO_SET_DEFAULT_STATE = 'STEP_TWO_SET_DEFAULT_STATE';
