export const SAVE_TRAINING_ID = 'SAVE_TRAINING_ID';
export const GET_CATALOG_CAMP_CAMP_ID = 'GET_CATALOG_CAMP_CAMP_ID';
export const TRAINING_SET_DEFAULT_STATE = 'TRAINING_SET_DEFAULT_STATE';
export const SET_SECONDARY_PROGRAM_ID = 'SET_SECONDARY_PROGRAM_ID';
