export const INCREMENT_WEEKS_COUNTER = 'INCREMENT_WEEKS_COUNTER';
export const DECREMENT_WEEKS_COUNTER = 'DECREMENT_WEEKS_COUNTER';
export const CUSTOMIZE_WEEK = 'CUSTOMIZE_WEEK';
export const SELECT_WEEK = 'SELECT_WEEK';
export const SET_WEEKS_COUNTER = 'SET_WEEKS_COUNTER';
